services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: social-network-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - DB_PATH=/app/socialnetwork.db
      - PORT=8080
    networks:
      - social-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social-network-frontend
    ports:
      - "5174:80"
    depends_on:
      backend:
        condition: service_started  # Wait for backend to start
    networks:
      - social-network
    restart: unless-stopped

networks:
  social-network:
    driver: bridge
